export const SCENE_KEYS = Object.freeze({
  PRELOAD_SCENE: 'PRELOAD_SCENE',
  CONVERSATION_SCENE: 'CONVERSATION_SCENE',
  WORLD_SCENE: 'WORLD_SCENE',
  MINI_GAME_SCENE: 'MINI_GAME_SCENE',
  TITLE_SCENE: 'TITLE_SCENE',
  APPLICATION_SCENE: 'APPLICATION_SCENE',
});
